[package]
name = "RobloxShortcutRemover"
version = "0.1.0"
edition = "2021"

[build]
target = "x86_64-pc-windows-msvc"

[dependencies]
dirs = "2.0.2"

[profile.release]
opt-level = "z"  # Optimize for size
panic = "abort"